import type { AuthUser } from "../services/api/authApi";

/** In-memory hackathon identity — no login / cookies required. */
export const LOCAL_DEMO_USER: AuthUser = {
  id: "demo-local-mohammed",
  email: "mohammed@grcx.local",
  username: "mohammed",
  full_name: "Mohammed",
  department: "GRC",
  is_active: true,
  is_manager: true,
  roles: ["Admin"],
  permissions: [
    "cases:read",
    "cases:write",
    "risk:read",
    "risk:write",
    "compliance:read",
    "compliance:write",
    "identity:read",
    "identity:write",
    "bcm:read",
    "dr:read",
    "reports:read",
    "reports:write",
    "users:admin",
    "audit:read",
    "ai:use",
    "governance:read",
    "governance:policies:create",
    "governance:policies:update",
    "governance:policies:submit",
    "governance:policies:approve",
    "governance:policies:publish",
    "governance:policies:archive",
    "governance:policies:upload",
    "governance:kpis:create",
    "governance:kpis:update",
    "governance:kpis:import",
    "governance:kpis:export",
    "governance:kpis:measure",
    "governance:kpis:upload",
  ],
};
