import { jsPDF, GState } from "jspdf";
import type { Report, ReportClassification } from "../mocks/types/reports";
import { displayFirstName } from "../utils/reportDisplay";
import logoUrl from "../assets/images/GRCx Logo.png";

const MARGIN = 25;
const PAGE_W = 210;
const PAGE_H = 297;
const CONTENT_W = PAGE_W - MARGIN * 2;
const ACCENT: [number, number, number] = [37, 99, 235];
const TEXT: [number, number, number] = [15, 23, 42];
const MUTED: [number, number, number] = [100, 116, 139];
const BORDER: [number, number, number] = [226, 232, 240];

const HEADER_H = 28;
const FOOTER_H = 18;
const CONTENT_TOP = MARGIN + HEADER_H;
const CONTENT_BOTTOM = PAGE_H - MARGIN - FOOTER_H;

let cachedLogo: string | null = null;

async function loadLogoDataUrl(): Promise<string | null> {
  if (cachedLogo) return cachedLogo;
  try {
    const response = await fetch(logoUrl);
    const blob = await response.blob();
    cachedLogo = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result));
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
    return cachedLogo;
  } catch {
    return null;
  }
}

function classificationColor(c: ReportClassification): {
  fill: [number, number, number];
  text: [number, number, number];
} {
  switch (c) {
    case "Top Secret":
      return { fill: [254, 226, 226], text: [185, 28, 28] };
    case "Restricted":
      return { fill: [254, 243, 199], text: [180, 83, 9] };
    case "Confidential":
      return { fill: [219, 234, 254], text: [29, 78, 216] };
    default:
      return { fill: [241, 245, 249], text: [71, 85, 105] };
  }
}

function wrapText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number
): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

function drawTextWatermark(
  doc: jsPDF,
  text: string,
  opacity: number,
  pageW: number,
  pageH: number
) {
  doc.saveGraphicsState();
  doc.setGState(new GState({ opacity: opacity / 100 }));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(52);
  doc.setTextColor(180, 180, 180);

  const cx = pageW / 2;
  const cy = pageH / 2;
  doc.text(text.toUpperCase(), cx, cy, {
    align: "center",
    angle: -35,
  });
  doc.restoreGraphicsState();
}

function drawClassificationBadge(
  doc: jsPDF,
  classification: ReportClassification,
  x: number,
  y: number
) {
  const colors = classificationColor(classification);
  const label = classification.toUpperCase();
  const w = Math.max(28, label.length * 2.2 + 8);
  doc.setFillColor(...colors.fill);
  doc.setDrawColor(...colors.text);
  doc.setLineWidth(0.2);
  doc.roundedRect(x - w, y - 5, w, 7, 1.5, 1.5, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...colors.text);
  doc.text(label, x - w / 2, y, { align: "center" });
}

function drawPageHeader(
  doc: jsPDF,
  report: Report,
  logo: string | null,
  pageW: number
) {
  const y0 = MARGIN - 2;

  if (logo) {
    try {
      doc.addImage(logo, "PNG", MARGIN, y0 - 4, 22, 9);
    } catch {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...ACCENT);
      doc.text("GRCx", MARGIN, y0 + 2);
    }
  } else {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...ACCENT);
    doc.text("GRCx", MARGIN, y0 + 2);
  }

  drawClassificationBadge(doc, report.classification, pageW - MARGIN, y0 + 2);

  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y0 + 8, pageW - MARGIN, y0 + 8);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(...TEXT);
  const title = report.name.length > 58 ? `${report.name.slice(0, 55)}…` : report.name;
  doc.text(title, MARGIN, y0 + 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(
    `v${report.version}  ·  ${report.issueDate}`,
    pageW - MARGIN,
    y0 + 14,
    { align: "right" }
  );

  doc.line(MARGIN, y0 + 17, pageW - MARGIN, y0 + 17);
}

function drawPageFooter(
  doc: jsPDF,
  report: Report,
  pageNum: number,
  pageCount: number,
  pageW: number
) {
  const y = PAGE_H - MARGIN + 2;
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y - 5, pageW - MARGIN, y - 5);

  const author = displayFirstName(report.generatedBy);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...MUTED);

  doc.text(
    `Generated By: ${author}  ·  Department: ${report.department}  ·  Position: ${report.userPosition}`,
    MARGIN,
    y
  );
  doc.text(
    `${report.issueDate}  ·  ${report.generatedTime}  ·  ${report.dayOfWeek}`,
    pageW / 2,
    y,
    { align: "center" }
  );
  doc.text(`Page ${pageNum} of ${pageCount}`, pageW - MARGIN, y, {
    align: "right",
  });
}

function drawSectionDivider(doc: jsPDF, title: string, y: number): number {
  doc.setFillColor(...ACCENT);
  doc.rect(MARGIN, y, 3, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...TEXT);
  doc.text(title, MARGIN + 6, y + 4.5);
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.2);
  doc.line(MARGIN + 6, y + 6, PAGE_W - MARGIN, y + 6);
  return y + 12;
}

function drawKpiRow(
  doc: jsPDF,
  metrics: Array<{ label: string; value: string }>,
  y: number
): number {
  const count = Math.min(metrics.length, 4);
  const colW = CONTENT_W / count;
  metrics.slice(0, count).forEach((metric, i) => {
    const x = MARGIN + i * colW;
    doc.setDrawColor(...BORDER);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(x + 1, y, colW - 3, 18, 2, 2, "FD");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(metric.label, x + 4, y + 6);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...ACCENT);
    doc.text(metric.value, x + 4, y + 14);
  });
  return y + 24;
}

function drawCoverPage(doc: jsPDF, report: Report, logo: string | null) {
  drawPageHeader(doc, report, logo, PAGE_W);

  let y = CONTENT_TOP + 16;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(...TEXT);
  const titleLines = doc.splitTextToSize(report.name, CONTENT_W) as string[];
  doc.text(titleLines, PAGE_W / 2, y, { align: "center" });
  y += titleLines.length * 11 + 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text(report.organizationName, PAGE_W / 2, y, { align: "center" });
  y += 14;

  const badgeColors = classificationColor(report.classification);
  doc.setFillColor(...badgeColors.fill);
  doc.setDrawColor(...badgeColors.text);
  const badgeLabel = report.classification.toUpperCase();
  const badgeW = badgeLabel.length * 2.8 + 12;
  doc.roundedRect((PAGE_W - badgeW) / 2, y - 5, badgeW, 9, 2, 2, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...badgeColors.text);
  doc.text(badgeLabel, PAGE_W / 2, y, { align: "center" });
  y += 20;

  doc.setDrawColor(...BORDER);
  doc.line(MARGIN + 20, y, PAGE_W - MARGIN - 20, y);
  y += 14;

  const author = displayFirstName(report.generatedBy);
  const metaRows: Array<[string, string]> = [
    ["Reporting Period", report.reportingPeriod],
    ["Generated Date", report.issueDate],
    ["Generated Time", report.generatedTime],
    ["Generated By", author],
    ["Department", report.department],
    ["Role", report.userPosition],
    ["Version", report.version],
    ["Report ID", report.reportId],
  ];

  doc.setFontSize(9.5);
  for (const [label, value] of metaRows) {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(label, MARGIN + 30, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...TEXT);
    doc.text(value || "—", MARGIN + 72, y);
    y += 8;
  }

  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  wrapText(
    doc,
    "This document is generated by GRCx and is intended for authorized recipients only. Distribution outside the organization requires explicit approval.",
    MARGIN + 16,
    y,
    CONTENT_W - 32,
    4
  );
}

function drawExecutiveContent(doc: jsPDF, report: Report): number {
  let y = CONTENT_TOP + 4;
  let pageNum = doc.getNumberOfPages();

  const ensureSpace = (needed: number) => {
    if (y + needed > CONTENT_BOTTOM) {
      doc.addPage();
      pageNum = doc.getNumberOfPages();
      y = CONTENT_TOP + 4;
    }
  };

  if (report.content.executiveNarrative) {
    ensureSpace(30);
    y = drawSectionDivider(doc, "Executive Summary", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT);
    y = wrapText(
      doc,
      report.content.executiveNarrative,
      MARGIN,
      y,
      CONTENT_W,
      5
    );
    y += 10;
  }

  if (report.content.summaryMetrics.length) {
    ensureSpace(28);
    y = drawSectionDivider(doc, "Key Performance Indicators", y);
    y = drawKpiRow(doc, report.content.summaryMetrics, y);
    y += 6;
  }

  for (const page of report.content.pages) {
    for (const section of page.sections) {
      ensureSpace(22);
      y = drawSectionDivider(doc, section.title, y);

      if (section.summary) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        doc.setTextColor(...TEXT);
        y = wrapText(doc, section.summary, MARGIN, y, CONTENT_W, 4.8);
        y += 4;
      }

      if (section.bullets?.length) {
        doc.setFontSize(9);
        for (const bullet of section.bullets.slice(0, 6)) {
          ensureSpace(10);
          doc.setTextColor(...ACCENT);
          doc.text("▸", MARGIN + 2, y);
          doc.setTextColor(...TEXT);
          y = wrapText(doc, bullet, MARGIN + 8, y, CONTENT_W - 8, 4.5);
          y += 2;
        }
        y += 4;
      }
    }
  }

  if (report.content.keyRecommendations.length) {
    ensureSpace(24);
    y = drawSectionDivider(doc, "Recommendations", y);
    doc.setFontSize(9);
    for (const rec of report.content.keyRecommendations.slice(0, 5)) {
      ensureSpace(10);
      doc.setTextColor(...ACCENT);
      doc.text("•", MARGIN + 2, y);
      doc.setTextColor(...TEXT);
      y = wrapText(doc, rec, MARGIN + 8, y, CONTENT_W - 8, 4.5);
      y += 2;
    }
  }

  return pageNum;
}

function drawDetailedContent(doc: jsPDF, report: Report): number {
  let y = CONTENT_TOP + 4;

  const ensureSpace = (needed: number) => {
    if (y + needed > CONTENT_BOTTOM) {
      doc.addPage();
      y = CONTENT_TOP + 4;
    }
  };

  if (report.content.summaryMetrics.length) {
    y = drawSectionDivider(doc, "Summary KPIs", y);
    y = drawKpiRow(doc, report.content.summaryMetrics, y);
    y += 8;
  }

  for (const page of report.content.pages) {
    for (const section of page.sections) {
      ensureSpace(20);
      y = drawSectionDivider(doc, section.title, y);

      if (section.summary) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...TEXT);
        y = wrapText(doc, section.summary, MARGIN, y, CONTENT_W, 4.5);
        y += 4;
      }

      if (section.bullets?.length) {
        doc.setFontSize(8.5);
        for (const bullet of section.bullets) {
          ensureSpace(8);
          doc.setTextColor(...MUTED);
          doc.text("•", MARGIN + 2, y);
          doc.setTextColor(...TEXT);
          y = wrapText(doc, bullet, MARGIN + 8, y, CONTENT_W - 8, 4.2);
          y += 1;
        }
        y += 4;
      }

      if (section.columns?.length && section.rows?.length) {
        const cols = section.columns;
        const colW = CONTENT_W / cols.length;
        ensureSpace(12);
        doc.setFillColor(241, 245, 249);
        doc.rect(MARGIN, y, CONTENT_W, 7, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7);
        doc.setTextColor(...TEXT);
        cols.forEach((col, i) => {
          doc.text(col.slice(0, 20), MARGIN + 2 + i * colW, y + 4.5);
        });
        y += 7;

        doc.setFont("helvetica", "normal");
        doc.setTextColor(51, 65, 85);
        for (const row of section.rows.slice(0, 20)) {
          ensureSpace(7);
          doc.setDrawColor(...BORDER);
          doc.line(MARGIN, y + 5, MARGIN + CONTENT_W, y + 5);
          cols.forEach((col, i) => {
            doc.text(String(row[col] ?? "—").slice(0, 24), MARGIN + 2 + i * colW, y + 4);
          });
          y += 6;
        }
        y += 6;
      }
    }
  }

  return doc.getNumberOfPages();
}

function applyPageChrome(
  doc: jsPDF,
  report: Report,
  logo: string | null,
  pageCount: number
) {
  const watermarkText =
    report.watermark?.text || report.classification.toUpperCase();
  const opacity = report.watermark?.opacity ?? 6;

  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    drawTextWatermark(doc, watermarkText, opacity, PAGE_W, PAGE_H);
    drawPageHeader(doc, report, logo, PAGE_W);
    drawPageFooter(doc, report, i, pageCount, PAGE_W);
  }
}

export async function buildEnterprisePdf(report: Report): Promise<{
  arrayBuffer: ArrayBuffer;
  dataUrl: string;
  pageCount: number;
  blob: Blob;
}> {
  const logo = await loadLogoDataUrl();
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const author = displayFirstName(report.generatedBy);
  doc.setProperties({
    title: report.name,
    subject: `${report.reportType} — ${report.classification}`,
    author,
    keywords: `${report.classification}, GRCx, ${report.reportType}, ${report.organizationName}`,
    creator: "GRCx Platform",
  });

  drawCoverPage(doc, report, logo);
  doc.addPage();

  if (report.category === "Executive") {
    drawExecutiveContent(doc, report);
  } else {
    drawDetailedContent(doc, report);
  }

  const pageCount = doc.getNumberOfPages();
  applyPageChrome(doc, report, logo, pageCount);

  const arrayBuffer = doc.output("arraybuffer") as ArrayBuffer;
  const dataUrl = doc.output("datauristring");
  const blob = new Blob([arrayBuffer], { type: "application/pdf" });

  return { arrayBuffer, dataUrl, pageCount, blob };
}

export function downloadPdfBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename.endsWith(".pdf") ? filename : `${filename}.pdf`;
  anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 30_000);
}

export function dataUrlToBlob(dataUrl: string): Blob {
  const [header, base64] = dataUrl.split(",");
  const mime = /data:(.*?);base64/.exec(header)?.[1] ?? "application/pdf";
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return new Blob([bytes], { type: mime });
}
