import { useEffect, useId, useRef } from "react";
import { Eye, X } from "lucide-react";
import type { Report } from "../../mocks/types/reports";
import Button from "../common/Button";
import { DownloadPdfButton } from "../common/DataTransferButton";
import ReportStatusBadge from "./ReportStatusBadge";
import styles from "./ReportDetailsDrawer.module.css";

interface ReportDetailsDrawerProps {
  report: Report | null;
  open: boolean;
  onClose: () => void;
  onPreview: (report: Report) => void;
  onDownload: (report: Report) => void;
}

export default function ReportDetailsDrawer({
  report,
  open,
  onClose,
  onPreview,
  onDownload,
}: ReportDetailsDrawerProps) {
  const titleId = useId();
  const closeRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    if (!open) return;
    closeRef.current?.focus();
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };
    document.addEventListener("keydown", onKeyDown);
    const previous = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      document.body.style.overflow = previous;
    };
  }, [open, onClose]);

  if (!open || !report) return null;

  return (
    <div className={styles.overlay} role="presentation" onClick={onClose}>
      <aside
        className={styles.drawer}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        onClick={(event) => event.stopPropagation()}
      >
        <header className={styles.header}>
          <div>
            <p className={styles.eyebrow}>{report.reportId}</p>
            <h2 id={titleId}>{report.name}</h2>
          </div>
          <button
            ref={closeRef}
            type="button"
            className={styles.close}
            aria-label="Close report details"
            onClick={onClose}
          >
            <X size={18} aria-hidden />
          </button>
        </header>

        <div className={styles.body}>
          <div className={styles.badges}>
            <ReportStatusBadge status={report.status} />
            <span>{report.reportType}</span>
          </div>

          <dl className={styles.meta}>
            {(
              [
                ["Issue date", report.issueDate],
                ["Reporting period", report.reportingPeriod],
                ["Auditor", `${report.auditor} · ${report.auditorRole}`],
                ["Generated by", report.generatedBy],
                ["Frameworks", report.frameworks.join(", ")],
                ["Modules", report.scope.modules.join(", ")],
                ["Pages", String(report.pages || "—")],
                ["Created", report.createdAt],
                ["Approval status", report.approvalStatus],
                [
                  "Watermark",
                  report.watermarkEnabled
                    ? `Enabled (${report.watermark.text})`
                    : "Disabled",
                ],
              ] as const
            ).map(([label, value]) => (
              <div key={label}>
                <dt>{label}</dt>
                <dd>{value}</dd>
              </div>
            ))}
          </dl>

          <div className={styles.actions}>
            <Button variant="secondary" onClick={() => onPreview(report)}>
              <Eye size={16} aria-hidden />
              Preview
            </Button>
            <DownloadPdfButton onClick={() => onDownload(report)} />
          </div>
        </div>
      </aside>
    </div>
  );
}
