import type { ModuleImportSchema } from "./types";

const RISK_LEVELS = ["Low", "Medium", "High", "Critical"] as const;
const DATE_GUIDANCE = "Use YYYY-MM-DD dates (Excel date cells are converted automatically).";

export const identitySchema: ModuleImportSchema = {
  moduleId: "identity",
  moduleLabel: "Identity & Access",
  uniqueKey: "id",
  displayNameKey: "employee",
  filenamePrefix: "Identity_Access",
  sheetName: "Identity Access",
  fields: [
    {
      key: "id",
      header: "Identity ID",
      required: true,
      unique: true,
      aliases: ["employeeId", "Employee ID", "Employee Number", "identityId"],
      maxLength: 64,
    },
    {
      key: "employee",
      header: "Employee Name",
      required: true,
      aliases: ["Full Name", "employeeName", "Name"],
      maxLength: 120,
    },
    { key: "email", header: "Email", required: true, maxLength: 160 },
    {
      key: "department",
      header: "Department",
      required: true,
      aliases: ["Division"],
      maxLength: 80,
    },
    { key: "role", header: "Role", required: true, maxLength: 80 },
    {
      key: "lastLogin",
      header: "Last Login",
      type: "date",
      aliases: ["Last Login Date"],
      maxLength: 40,
    },
    {
      key: "currentActivity",
      header: "Current Activity",
      maxLength: 200,
    },
    {
      key: "behaviorStatus",
      header: "Behavior Status",
      type: "enum",
      enumValues: [
        "Normal",
        "Baseline Matched",
        "Minor Deviation",
        "Suspicious Activity",
        "Behavior Anomaly",
      ],
    },
    {
      key: "riskLevel",
      header: "Risk Level",
      type: "enum",
      enumValues: RISK_LEVELS,
      aliases: ["Risk Rating"],
    },
    {
      key: "policyStatus",
      header: "Policy Status",
      type: "enum",
      enumValues: [
        "Compliant",
        "Policy Warning",
        "Policy Violation",
        "Unauthorized Activity",
      ],
    },
    {
      key: "recommendedAction",
      header: "Recommended Action",
      type: "enum",
      enumValues: [
        "No Action",
        "Review Activity",
        "Force MFA",
        "Reset Password",
        "Disable Account",
        "Investigate",
        "Escalate to SOC",
      ],
    },
  ],
  instructions: [
    "Unique identifier: Identity ID (employeeId / identityId).",
    DATE_GUIDANCE,
    `Allowed risk levels: ${RISK_LEVELS.join(", ")}.`,
    "Allowed policy statuses: Compliant, Policy Warning, Policy Violation, Unauthorized Activity.",
  ],
};

export const grcCasesSchema: ModuleImportSchema = {
  moduleId: "grc-cases",
  moduleLabel: "SOAR Queue",
  uniqueKey: "caseId",
  displayNameKey: "title",
  filenamePrefix: "SOAR_Queue",
  sheetName: "GRC Cases",
  fields: [
    {
      key: "caseId",
      header: "Case ID",
      required: true,
      unique: true,
      aliases: ["GRC Case ID", "Case Number"],
      maxLength: 64,
    },
    { key: "title", header: "Title", required: true, maxLength: 200 },
    {
      key: "status",
      header: "Status",
      required: true,
      type: "enum",
      enumValues: [
        "New",
        "Assigned",
        "In Progress",
        "Pending Evidence",
        "Pending Approval",
        "Resolved",
        "Closed",
        "Rejected",
        "Archived",
      ],
    },
    {
      key: "severity",
      header: "Severity",
      type: "enum",
      enumValues: RISK_LEVELS,
      aliases: ["Priority"],
    },
    { key: "assignedTo", header: "Assigned To", required: true, maxLength: 80, aliases: ["Assigned Analyst", "Owner"] },
    { key: "department", header: "Department", maxLength: 80 },
    { key: "source", header: "Source", maxLength: 80 },
    { key: "framework", header: "Framework", maxLength: 80, aliases: ["Related Module"] },
    { key: "control", header: "Control", maxLength: 120 },
    { key: "affectedAsset", header: "Affected Asset", maxLength: 120 },
    { key: "createdAt", header: "Created Time", type: "date", maxLength: 40, aliases: ["Opened Date"] },
    { key: "updatedAt", header: "Last Updated", type: "date", maxLength: 40 },
    { key: "slaDueAt", header: "SLA Due", type: "date", maxLength: 40, aliases: ["Due Date"] },
    { key: "description", header: "Description", maxLength: 500, aliases: ["Summary"] },
  ],
  instructions: [
    "Unique identifier: Case ID.",
    DATE_GUIDANCE,
    `Allowed severities: ${RISK_LEVELS.join(", ")}.`,
    "Source is typically SOAR for inbound governance cases.",
  ],
};

export const riskSchema: ModuleImportSchema = {
  moduleId: "risk",
  moduleLabel: "Risk Assessment",
  uniqueKey: "caseId",
  displayNameKey: "title",
  filenamePrefix: "Risk_Assessment",
  sheetName: "Risk Cases",
  fields: [
    {
      key: "caseId",
      header: "Case ID",
      required: true,
      unique: true,
      aliases: ["riskId", "Risk ID", "Risk Case ID"],
      maxLength: 64,
    },
    { key: "title", header: "Title", required: true, maxLength: 200 },
    { key: "category", header: "Category", required: true, maxLength: 80 },
    { key: "affectedAsset", header: "Affected Asset", maxLength: 120 },
    { key: "department", header: "Department", required: true, maxLength: 80 },
    { key: "owner", header: "Owner", required: true, maxLength: 80 },
    { key: "source", header: "Source", maxLength: 80 },
    {
      key: "status",
      header: "Status",
      required: true,
      type: "enum",
      enumValues: [
        "Open",
        "Under Assessment",
        "Remediation in Progress",
        "Accepted",
        "Closed",
        "Archived",
      ],
    },
    {
      key: "inherentRisk",
      header: "Inherent Risk",
      type: "enum",
      enumValues: RISK_LEVELS,
    },
    {
      key: "residualRisk",
      header: "Residual Risk",
      type: "enum",
      enumValues: RISK_LEVELS,
    },
    { key: "createdDate", header: "Created Date", type: "date", maxLength: 40 },
    { key: "lastUpdated", header: "Last Updated", type: "date", maxLength: 40 },
    { key: "dueDate", header: "Due Date", type: "date", maxLength: 40 },
    { key: "description", header: "Description", maxLength: 1000 },
  ],
  instructions: [
    "Unique identifier: Case ID (riskId / caseId).",
    DATE_GUIDANCE,
    `Allowed risk levels: ${RISK_LEVELS.join(", ")}.`,
  ],
};

export const complianceSchema: ModuleImportSchema = {
  moduleId: "compliance",
  moduleLabel: "Asset Compliance",
  uniqueKey: "id",
  displayNameKey: "name",
  filenamePrefix: "Asset_Compliance",
  sheetName: "Asset Compliance",
  fields: [
    {
      key: "id",
      header: "Asset ID",
      required: true,
      unique: true,
      aliases: ["assetId", "Asset Number"],
      maxLength: 64,
    },
    { key: "name", header: "Asset Name", required: true, maxLength: 160 },
    {
      key: "assetType",
      header: "Asset Type",
      required: true,
      type: "enum",
      enumValues: [
        "Endpoint",
        "Server",
        "Employee",
        "Service Account",
        "Application",
        "Database",
        "Network Device",
        "Cloud Resource",
      ],
    },
    { key: "owner", header: "Owner", required: true, maxLength: 80 },
    { key: "department", header: "Department", required: true, maxLength: 80 },
    { key: "operatingSystem", header: "Operating System", maxLength: 80 },
    {
      key: "framework",
      header: "Framework",
      required: true,
      type: "enum",
      enumValues: ["NCA ECC", "SAMA CSF", "PCI DSS", "ISO 27001"],
    },
    {
      key: "complianceStatus",
      header: "Compliance Status",
      required: true,
      type: "enum",
      enumValues: [
        "Compliant",
        "Partially Compliant",
        "Non-Compliant",
        "Under Review",
      ],
    },
    {
      key: "riskLevel",
      header: "Risk Level",
      type: "enum",
      enumValues: RISK_LEVELS,
    },
    {
      key: "lastAssessment",
      header: "Last Assessment",
      type: "date",
      maxLength: 40,
    },
    { key: "failedControlId", header: "Failed Control ID", maxLength: 40 },
    { key: "failedControlName", header: "Failed Control Name", maxLength: 160 },
  ],
  instructions: [
    "Unique identifier: Asset ID.",
    DATE_GUIDANCE,
    `Allowed risk levels: ${RISK_LEVELS.join(", ")}.`,
  ],
};

export const bcmSchema: ModuleImportSchema = {
  moduleId: "bcm",
  moduleLabel: "Business Continuity",
  uniqueKey: "id",
  displayNameKey: "name",
  filenamePrefix: "Business_Continuity",
  sheetName: "Critical Processes",
  fields: [
    {
      key: "id",
      header: "Process ID",
      required: true,
      unique: true,
      aliases: ["processId", "Business Process ID", "BCM ID", "Service ID", "Recovery ID"],
      maxLength: 64,
    },
    {
      key: "name",
      header: "Business Process",
      required: true,
      aliases: ["Business Service", "Business Function", "System", "Process"],
      maxLength: 160,
    },
    {
      key: "businessUnit",
      header: "Business Unit",
      maxLength: 80,
      aliases: ["BU"],
    },
    { key: "department", header: "Department", required: true, maxLength: 80 },
    {
      key: "owner",
      header: "Owner",
      maxLength: 80,
      aliases: ["BCM Owner"],
    },
    {
      key: "criticality",
      header: "Criticality",
      type: "enum",
      enumValues: RISK_LEVELS,
    },
    {
      key: "businessImpact",
      header: "Business Impact",
      type: "enum",
      enumValues: ["Severe", "Major", "Moderate", "Minor"],
    },
    { key: "rto", header: "RTO", maxLength: 40 },
    { key: "rpo", header: "RPO", maxLength: 40 },
    { key: "mao", header: "MAO", maxLength: 40, aliases: ["Max Tolerable Downtime"] },
    {
      key: "recoveryStrategy",
      header: "Recovery Strategy",
      maxLength: 80,
      aliases: ["Recovery Method"],
    },
    {
      key: "dependencies",
      header: "Dependencies",
      maxLength: 400,
    },
    {
      key: "recoveryTeam",
      header: "Recovery Team",
      maxLength: 80,
    },
    {
      key: "status",
      header: "Status",
      type: "enum",
      enumValues: ["Ready", "Testing", "At Risk", "Draft", "Review", "Active"],
    },
    {
      key: "riskLevel",
      header: "Risk Level",
      type: "enum",
      enumValues: RISK_LEVELS,
    },
    { key: "lastTest", header: "Last Test", type: "date", maxLength: 40 },
    { key: "nextTest", header: "Next Test", type: "date", maxLength: 40 },
    { key: "nextReview", header: "Next Review", type: "date", maxLength: 40 },
    { key: "version", header: "Version", maxLength: 20 },
  ],
  instructions: [
    "Unique identifier: Process ID (duplicates are skipped or merged).",
    DATE_GUIDANCE,
    `Allowed risk / criticality: ${RISK_LEVELS.join(", ")}.`,
    "Status Active maps to Ready on import when validated by operators.",
  ],
};

export const drSchema: ModuleImportSchema = {
  moduleId: "dr",
  moduleLabel: "Disaster Recovery",
  uniqueKey: "id",
  displayNameKey: "system",
  filenamePrefix: "Disaster_Recovery",
  sheetName: "Critical Systems",
  fields: [
    {
      key: "id",
      header: "System ID",
      required: true,
      unique: true,
      aliases: ["systemId", "recoveryPlanId", "Plan ID"],
      maxLength: 64,
    },
    { key: "system", header: "System Name", required: true, maxLength: 160 },
    { key: "owner", header: "Owner", required: true, maxLength: 80 },
    {
      key: "priority",
      header: "Priority",
      type: "enum",
      enumValues: RISK_LEVELS,
    },
    {
      key: "recoveryStatus",
      header: "Recovery Status",
      type: "enum",
      enumValues: ["Operational", "Recovering", "Offline", "Pending"],
    },
    { key: "recoveryTime", header: "Recovery Time", maxLength: 40 },
    { key: "rto", header: "RTO", maxLength: 40 },
    { key: "rpo", header: "RPO", maxLength: 40 },
  ],
  instructions: [
    "Unique identifier: System ID (systemId / recoveryPlanId).",
    DATE_GUIDANCE,
    `Allowed priorities: ${RISK_LEVELS.join(", ")}.`,
  ],
};

export const governancePoliciesSchema: ModuleImportSchema = {
  moduleId: "governance-policies",
  moduleLabel: "Governance Policies",
  uniqueKey: "id",
  displayNameKey: "name",
  filenamePrefix: "Governance_Policies",
  sheetName: "Policies",
  fields: [
    {
      key: "id",
      header: "Policy ID",
      required: true,
      unique: true,
      aliases: ["policyId", "Policy Number"],
      maxLength: 64,
    },
    { key: "name", header: "Policy Name", required: true, maxLength: 160 },
    { key: "description", header: "Policy Description", maxLength: 2000 },
    { key: "category", header: "Policy Category", required: true, maxLength: 80 },
    { key: "department", header: "Department", required: true, maxLength: 80 },
    { key: "owner", header: "Owner", required: true, maxLength: 80 },
    { key: "approver", header: "Approver", maxLength: 80 },
    { key: "version", header: "Version", maxLength: 20 },
    { key: "effectiveDate", header: "Effective Date", type: "date", maxLength: 40 },
    {
      key: "nextReviewDate",
      header: "Next Review Date",
      type: "date",
      maxLength: 40,
    },
    { key: "reviewFrequency", header: "Review Frequency", maxLength: 40 },
    { key: "approvalStatus", header: "Approval Status", maxLength: 40 },
    { key: "policyStatus", header: "Policy Status", maxLength: 40 },
    { key: "frameworks", header: "Related Frameworks", maxLength: 240 },
    { key: "controls", header: "Related Controls", maxLength: 240 },
    { key: "notes", header: "Notes", maxLength: 1000 },
    { key: "lastUpdated", header: "Last Updated", type: "date", maxLength: 40 },
  ],
  instructions: [
    "Unique identifier: Policy ID.",
    "Policy document files must be uploaded separately — do not embed binaries in Excel.",
    DATE_GUIDANCE,
  ],
};

export const governanceKpisSchema: ModuleImportSchema = {
  moduleId: "governance-kpis",
  moduleLabel: "Governance KPIs",
  uniqueKey: "id",
  displayNameKey: "name",
  filenamePrefix: "Governance_KPIs",
  sheetName: "KPIs",
  fields: [
    {
      key: "id",
      header: "KPI ID",
      required: true,
      unique: true,
      aliases: ["kpiId", "KPI Number"],
      maxLength: 64,
    },
    { key: "name", header: "KPI Name", required: true, maxLength: 160 },
    { key: "description", header: "Description", maxLength: 2000 },
    { key: "category", header: "Category", required: true, maxLength: 80 },
    { key: "department", header: "Department", required: true, maxLength: 80 },
    { key: "owner", header: "Owner", required: true, maxLength: 80 },
    { key: "frequency", header: "Frequency", maxLength: 40 },
    { key: "unit", header: "Unit", maxLength: 40 },
    { key: "formula", header: "Formula", maxLength: 400 },
    {
      key: "direction",
      header: "Performance Direction",
      type: "enum",
      enumValues: ["Higher Is Better", "Lower Is Better", "Target Range"],
    },
    { key: "target", header: "Target", type: "number", maxLength: 40 },
    {
      key: "warningThreshold",
      header: "Warning Threshold",
      type: "number",
      maxLength: 40,
    },
    {
      key: "criticalThreshold",
      header: "Critical Threshold",
      type: "number",
      maxLength: 40,
    },
    { key: "currentValue", header: "Current Value", type: "number", maxLength: 40 },
    { key: "dataSource", header: "Data Source", maxLength: 80 },
    {
      key: "periodStart",
      header: "Reporting Period Start",
      type: "date",
      maxLength: 40,
    },
    {
      key: "periodEnd",
      header: "Reporting Period End",
      type: "date",
      maxLength: 40,
    },
    { key: "lastUpdated", header: "Last Updated", type: "date", maxLength: 40 },
    { key: "notes", header: "Notes", maxLength: 1000 },
  ],
  instructions: [
    "Unique identifier: KPI ID.",
    "Accepted Excel only (.xlsx / .xls). CSV and documents are rejected.",
    DATE_GUIDANCE,
  ],
};

export const MODULE_SCHEMAS: Record<string, ModuleImportSchema> = {
  identity: identitySchema,
  "grc-cases": grcCasesSchema,
  risk: riskSchema,
  compliance: complianceSchema,
  bcm: bcmSchema,
  dr: drSchema,
  "governance-policies": governancePoliciesSchema,
  "governance-kpis": governanceKpisSchema,
};

export function getModuleSchema(moduleId: string): ModuleImportSchema {
  const schema = MODULE_SCHEMAS[moduleId];
  if (!schema) {
    throw new Error(`Unknown module schema: ${moduleId}`);
  }
  return schema;
}
